version: '3.3'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
     - 27019:27017

    restart: always
    volumes: 
      - "mongodb_data_container:/data/db"


  app:
    build: .
    ports:
     - 4000:4000
    env_file:
      - ./config/config.env
    # environment:
    #  - PORT=4000
    #  - MONGO_URI=mongodb://localhost:27019/maatnoGram_db
    entrypoint: "npm start"
    depends_on:
      - mongo_db
  

volumes:
  mongodb_data_container:
